# 配置 datasource
spring:
  datasource:
    url: jdbc:mysql:///springboot?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


# mybatis 使用xml时,需要配置
mybatis:
  # mapper映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  # 配置包名
  type-aliases-package: com.itheima.springbootmybatis.domain